# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Qdialog(object):
    def setupUi(self, Qdialog):
        Qdialog.setObjectName("Qdialog")
        Qdialog.resize(877, 496)
        Qdialog.setStyleSheet("\n"
"background-color: rgb(70, 70, 70);")
        self.pushButton = QtWidgets.QPushButton(Qdialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 17, 271, 181))
        self.pushButton.setStyleSheet("font: 28pt \"MS Reference Sans Serif\"; \n"
"background-color: rgb(85, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Qdialog)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 20, 271, 181))
        self.pushButton_2.setStyleSheet("font: 28pt \"MS Reference Sans Serif\"; \n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Qdialog)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 260, 271, 181))
        self.pushButton_3.setStyleSheet("font: 28pt \"MS Reference Sans Serif\"; \n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Qdialog)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 260, 271, 181))
        self.pushButton_4.setStyleSheet("font: 28pt \"MS Reference Sans Serif\"; \n"
"background-color: rgb(85, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(Qdialog)
        QtCore.QMetaObject.connectSlotsByName(Qdialog)

    def retranslateUi(self, Qdialog):
        _translate = QtCore.QCoreApplication.translate
        Qdialog.setWindowTitle(_translate("Qdialog", "Dialog"))
        self.pushButton.setText(_translate("Qdialog", "LÝ THUYẾT"))
        self.pushButton_2.setText(_translate("Qdialog", "BÀI TẬP"))
        self.pushButton_3.setText(_translate("Qdialog", "XẾP HẠNG"))
        self.pushButton_4.setText(_translate("Qdialog", "KIỂM TRA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Qdialog = QtWidgets.QDialog()
    ui = Ui_Qdialog()
    ui.setupUi(Qdialog)
    Qdialog.show()
    sys.exit(app.exec_())
